from . import dashboard
from . import alumno
from . import examen
from . import criterio_calificacion
from . import evento_examen
from . import reporte_ganancias
from . import retiro_socio
from . import examen_aditamento
from . import torneo
